### ISSUE TITLE
Onhandige volgorde styles/script/html

### ISSUE THREAD

**Issue by rutgerkock** [Lmikkers/your-tribe-for-life-profile-card#3]
Zou je styling onderaan zetten, dit is onoverzichtelijk
https://github.com/Lmikkers/your-tribe-for-life-profile-card/blob/3f1b8868be3d8a31d71a56da7a4d370c9365b9bd/src/routes/%2Bpage.svelte#L1-L125

**Comment by Lmikkers** [comment]
Thanks heb het aangepast!
