### ISSUE TITLE
gewoon rotate werkt :)

### ISSUE THREAD

**Issue by rutgerkock** [Lmikkers/your-tribe-for-life-profile-card#4]
Je kan gewoon rotateY: 180deg; gebruiken

https://github.com/Lmikkers/your-tribe-for-life-profile-card/blob/3f1b8868be3d8a31d71a56da7a4d370c9365b9bd/src/routes/%2Bpage.svelte#L95

**Comment by Lmikkers** [comment]
Thanks ik ga er naar kijken!
